# Generated by Django 5.1.3 on 2024-12-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzbektube', '0002_alter_category_options_alter_videocontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzbektube.videocontent', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Comment date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzbektube.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Publication'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=150, verbose_name='Profile name')),
                ('nick_name', models.CharField(default='@user', max_length=150, verbose_name='Nickname ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
