# Generated by Django 5.1.3 on 2024-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzbektube', '0004_alter_profile_options_videocontent_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='user IP')),
            ],
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='views',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='content_views', to='uzbektube.ip', verbose_name='IP views'),
        ),
    ]
